# Generated by Django 4.2.6 on 2023-10-19 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.PositiveIntegerField(default=19438333, unique=True, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
