# Generated by Django 4.2.6 on 2023-10-19 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0002_alter_account_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.PositiveIntegerField(default=25858309, unique=True, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
