# Generated by Django 4.2.6 on 2023-10-20 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0003_remove_account_user_alter_account_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.PositiveIntegerField(default=88472895, unique=True, validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
